### ISSUE TITLE
Polish Circles

### ISSUE THREAD

**Issue by dbuscaglia** [quipit/quipit-android#40]
### Tasks
- [ ] Circles need to persist their icon and background image
- [ ] Background icon needs to be clean for marshaling around
- [ ] Navbar circle menu: get rid of stubs
- [ ] Navbar circle menu needs to be styled with image of circle icon and app theme
