### ISSUE TITLE
Polish Quips

### ISSUE THREAD

**Issue by dbuscaglia** [quipit/quipit-android#41]
### Tasks
- [ ] Quips need to have background images
- [ ] Quips need geo location
- [ ] Quip item xml needs style
- [ ] Compose View needs to be styled
